stages:
  - build
  - lint

default:
  image: node:lts-alpine
  before_script:
    - apk add --no-cache build-base jpeg-dev zlib-dev autoconf automake libtool libpng-dev
    - npm i -g yarn
    - yarn install --frozen-lockfile

build:
  stage: build
  script:
    - yarn build
  after_script:
    - yarn gulp clean
  artifacts:
    expire_in: 10 min
    paths:
      - node_modules/

prettier:
  stage: lint
  script:
    - yarn prettier --check "src/**/*.{ts,js}"

stylelint:
  stage: lint
  script:
    - yarn stylelint "src/**/*.{css,scss}"

tslint:
  stage: lint
  script:
    - yarn tslint -c tslint.js "src/**/*.{ts,js}" -e "src/**/vendor?(s)/**/*"
